# Generated by Django 4.2.11 on 2025-10-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('is_enable', models.BooleanField(default=False)),
                ('publish_date', models.DateField()),
                ('created_time', models.DateField()),
                ('uploaded_time', models.DateField()),
            ],
        ),
    ]
