# Generated by Django 4.2.11 on 2025-10-27 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_uploaded_time_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_enable',
        ),
    ]
